# pub keys
keys:
  - &dev age1w4zh3zu6xq94t6y9mjahh94h7wdv0k65yshwsmel97ywdw50qucq5pxk2f
  - &users:
    - &michael age18vflapckk4ueadtzplldm7955c8dkk92xsr03wdfwtexkju00pfskzxyur
  - &hosts:
    - &sephiroth age1rs6mku5sq3equ0av04fs5jasszlappt5zsrs9p7r9jf9mzk23dkqxl0xfp
    - &nova-1 age1z7e64rq7s7ht8yv78vf2axjuyt8v9d4f882q0kdzdzayxj00vydsmltmpq
    - &nova-2 age1we9pwc6ujmwh0m4ngtqevleaj8lf6w3huhdnz32e9c967uf9qdhsmpsdxl
    - &nova-3 age12cpmvtc0hmpfhz7ztrzstfz770qf5ss5jkyp7eqmfc04y7k8p4dqdhwpg2
    - &ganon age1xsvgfxddra4t835n70qvrapwy04qgcs5ydsj2famc8shhymyf4kqkj0d0r

creation_rules:
  #path should be relative to location of this file (.sops.yaml)
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *dev
          - *michael
          - *sephiroth
          - *nova-1
          - *nova-2
          - *nova-3
          - *ganon
